version: '2'
services:
  web:
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/app
    ports:
      - "3001:3001"
    environment: 
      - SECRET=NPH2xmMIKI78gsIZ/BPCCpy6u6MnLbFhT4Oj1S/zky0=
      - DATABASE_URL=mongodb://mongodb:27017/appointments
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
      - MONGO_DATA_DIR=/data/db
    volumes: 
      - ./data/db:/data/db
    command: mongod --smallfiles
